//Spec ops officer
/obj/structure/closet/secure_closet/nanotrasen_creed
	name = "NanoTrasen special operations officer's locker"
	req_access = list(access_cent_creed)
	closet_appearance = /decl/closet_appearance/secure_closet/nanotrasen/commander
	storage_capacity = 3.5 * MOB_MEDIUM
	starts_with = list(
		/obj/item/clothing/under/syndicate/combat,
		/obj/item/clothing/suit/armor/swat/officer/nt,
		/obj/item/device/radio/headset/ert,
 		/obj/item/clothing/glasses/thermal/plain/eyepatch,
 		/obj/item/clothing/mask/smokable/cigarette/cigar/havana,
		/obj/item/clothing/suit/armor/swat,
		/obj/item/clothing/head/helmet/space/deathsquad,
		/obj/item/weapon/gun/energy/pulse_rifle/compact/admin,
		/obj/item/weapon/storage/backpack/satchel,
	 	/obj/item/clothing/shoes/boots/combat,
		/obj/item/clothing/gloves/combat,
		/obj/item/device/pda/ert/officer,
		/obj/item/clothing/head/beret,
		/obj/item/clothing/head/helmet/swat/beret/dsquad,
		/obj/item/weapon/gun/energy/pulse_rifle,
		/obj/item/clothing/head/helmet/dermal,
		/obj/item/device/radio/headset/ert,
		/obj/item/device/radio/headset/ert/alt,
		/obj/item/clothing/glasses/omnihud/all,
		/obj/item/clothing/glasses/thermal/plain/eyepatch,
		/obj/item/taperoll/police,
		/obj/item/weapon/storage/backpack/dufflebag,
		/obj/item/weapon/reagent_containers/spray/pepper,
		/obj/item/weapon/storage/fancy/cigar/havana,
		/obj/item/weapon/flame/lighter/zippo/gold,
		/obj/item/clothing/mask/gas/half,
		/obj/item/weapon/tool/crowbar/red,
		/obj/item/weapon/storage/box/flashbangs,
		/obj/item/weapon/storage/belt/security,
		/obj/item/device/flash,
		/obj/item/weapon/melee/baton/loaded,
		/obj/item/weapon/gun/energy/gun,
		/obj/item/weapon/cell/device/weapon,
		/obj/item/weapon/reagent_containers/pill/cyanide,
		/obj/item/clothing/accessory/holster/waist,
		/obj/item/weapon/melee/telebaton,
		/obj/item/device/flashlight/maglight,
		/obj/item/clothing/gloves/combat,
		/obj/item/clothing/shoes/boots/combat,
		/obj/item/weapon/rig/ert/assetprotection,
		/obj/item/clothing/under/syndicate/combat,
		/obj/item/clothing/under/nanotrasen/security/commander)